### ISSUE TITLE
[haxe] [OpenFL] Error when trying to delete the export directory

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#106]
```
Could not be recycled: C:\HaxeToolkit\haxe\lib\flixel-demos\git\Other\MinimalistTD\export

   at ProjectManager.Actions.FileActions.Delete(String path, Boolean confirm)
```

This issue seems to be unique to the export folder.

I think it might be related to the fact that FD recognizes `export\windows\neko\haxe` and `export\android\haxe` as classpaths (project properties -> classpaths), as the error only seems to occur when project was compiled to neko and / or android. I guess those are recognized as claspaths by FD because they contain `.hx` files.

Removing those directories from the classpaths doesn't seem to help, however, deleting the directories gets rid of the problem.

**Comment by sruloart** [comment]
@Gama11 did it fix that issue for you? because I've never stopped seeing this error. It's more noticeable with export\windows\neko, which would not allow you to rebuild your project without you deleting the executable yourself:
```
Called from ? line 1
Called from CommandLineTools.hx line 1359
Called from CommandLineTools.hx line 25
Called from CommandLineTools.hx line 126
Called from CommandLineTools.hx line 579
Called from lime/project/PlatformTarget.hx line 77
Called from lime/tools/platforms/WindowsPlatform.hx line 111
Called from lime/tools/helpers/NekoHelper.hx line 40
Called from /usr/lib/haxe/std/neko/_std/sys/io/File.hx line 54
Uncaught exception - [file_open,export/windows/neko/bin//OSQ.exe]
Build halted with errors.
```   
And it also happens with export\windows\cpp (if you have made some changes or cleaned your project):
```
Error: Cannot copy to "export/windows/cpp/bin//Exectuable_Name.exe", is the file in use?
Build halted with errors.
```
Now, what's weird is that with export\flash, while you still can't delete the directory yourself, you won't have any problem rebuilding your project (like the one I've mentioned here with the export\windows\ folders).

I'm using: Win7 64bit, FD 4.7.2, latest Lime/Openfl releases, Haxe 3.1.3.

**Comment by Gama11** [comment]
@sruloart I thought so... but I can reproduce the same issue with the latest FD version now, so I guess this needs to be reopened.
