### ISSUE TITLE
"haxelib dev" doesn't change the path used in FD

### ISSUE THREAD

**Issue by GimmickyApps** [fdorg/flashdevelop#1078]
I have a haxelib that I released and started using in a project.

Now, I'd like to change the code, and commit to the git repo as I go.  So I did "haxelib dev mylib /path/to/git/repo/", which succeeded with "Development directory set to...".

Even after restarting FD, though, if I press F4 when on a mylib class, it opens the one under C:\haxelib... rather than my git repo.

FD 5.0.2.2 on Win7/64.

**Comment by Gama11** [comment]
This is unlikely to be a FlashDevelop issue, it just uses the haxelib paths provided by Lime / OpenFL. What does `haxelib list mylib` say?

`export/<target>/haxe/debug.hxml` (or release.hxml) contains the arguments passed to the Haxe compiler by Lime, which is the same info FlashDevelop uses. What's the path there?

**Comment by GimmickyApps** [comment]
`haxelib list mylib` gives the correct git repo path I had given.

`debug.hxml` gives the C:\haxelib path instead.  What causes debug.hxml to be regenerated?

**Comment by Gama11** [comment]
So this is just Lime handling dev libraries incorrectly then. There's definitely some issues regarding how it handles `haxelib dev` and the `version` attribute (see https://github.com/openfl/lime/issues/686), but maybe the issue is more general than that.

Compiling for that target causes it to be generated.

Btw, I've personally found `haxelib dev` to be a major pain. I just use `haxelib git`, which works perfectly fine, and run `haxelib dev <lib>` afterwards to disable the development directory (since it causes issues like `haxelib set` failing silently).

**Comment by GimmickyApps** [comment]
Hmm...`haxelib git` said it installed from my local repo, but I'm still having the same issue, also after compiling and restarting FD and compiling again.  Thanks for the Lime link and for your help.  :)

**Comment by GimmickyApps** [comment]
Oops, besides, I put an underscore instead of a hyphen in my lib name.  Now it actually works...but before I swear I was having a similar issue but didn't manage to report it.  Oh well, I'll come back with something more solid if it happens again...
