### ISSUE TITLE
ProjectManager exception on delete when selection includes files and directories

### ISSUE THREAD

**Issue by Gama11** [fdorg/flashdevelop#1165]
I assume that's what causes it anyway. Deleting only files or only directories works.

![](http://i.imgur.com/HvbcILj.gif)

**Comment by Shenjoku** [comment]
The problem here is that you've selected a directory for delete as well as files within that directory. It deletes the directory first, deleting everything within, then it attempts to delete those files that no longer exist and the exception is thrown. It needs to be smarter about detecting that the file no longer exists before trying to delete it.
