### ISSUE TITLE
Identified as Malware in Windows 10

### ISSUE THREAD

**Issue by angelocky** [fdorg/flashdevelop#1272]
Tried to run Haxedevelop installer as downloaded from haxedevelop.org and Windows defender would not allow it. Says the file is identified as containing the Win32/Rundas!plock trojan.

**Comment by Neverbirth** [comment]
If I'm not wrong @elsassph is looking into this.

**Comment by elsassph** [comment]
There is something fishy for sure: I can do a local build of HaxeDevelop (using `buildl.cmd`) and these binaries are ok for Defender while I can't event download HD dev builds (neither setup or zip). Could the CI server be somehow compromised? @Meychi

**Comment by Neverbirth** [comment]
But then why does the build of FD not suffer from the same problem? Could it be related to how the CI server checks out some file? Or maybe is it only because when you compile the files by yourself Defender doesn't analyze the file in the same way? ie, differences in the MSBuild version, the "flag" that says that the file comes from outside, etc.

**Comment by angelocky** [comment]
I can confirm I was able to run the zipped, non installable version without interference from Defender, also, I know of some installer generator tools, such as some from Python, that get flagged as malware. So, the issue may also be related to the way the installer is created.

**Comment by elsassph** [comment]
Defender doesn't allow me to download the ZIP version of HaxeDevelop from the website. But I can build HaxeDevelop (like CI does) and the resulting ZIP is OK for Defender...

**Comment by tcorbet** [comment]
I don't know if this will help since it is from a different configuration environment, but I can report the same symptom with AVG running as my malware and FlashDevelop being executed from your .zip download, not from running the installer.

I have seen this message about three times since the first of the year -- it shows up anew whenever AVG does an upgrade of itself.  The PopUp warning allows the action to "IGNORE' which it will then do until they send a new update which will no longer honor the old "IGNORE" list.  The analysis function in AVG does not provide any details indicating what it was that made them think that running FlashDevelop.exe from the local file system would be a dangerous thing to do, so it is just becomes a one-time annoyance.

**Comment by hexaglow** [comment]
I just encountered this issue as well. VirusTotal shows alerts from 10 databases (https://www.virustotal.com/en/file/f1ed3374e567b03da1da39fcadf6956e6c9e14ff46435e8e0ce019293c4f25bd/analysis/1467213021/), with the common theme being Trojans, so it's not just flaky detection, there's something more to it than that.

**Comment by Meychi** [comment]
I reported the issue to the Microsoft Malware Protection Center and day later they reported it should be fixed. Update the definitions an please try again! 

For other AV apps i can't say anything, please just report these so they fix these incorrect detections.

**Comment by SlavaRa** [comment]
I think that this issue can be closed
