### ISSUE TITLE
why flashdevelop auto close when  open  openfl project which use [thx,core] library?

### ISSUE THREAD

**Issue by Liu-GuangYong** [fdorg/flashdevelop#1276]
Hi, today i reinstall the operating system and i found some old project is not work.
now my computer system : Win7 64bit  
flashdevelop version :5.1.1.1
java version "1.6.0-rc"
haxe version : 3.3.0
haxe libs version :
actuate: [1.8.6]
format: [3.2.1]
lime: [2.9.1]
nme: [5.6.4]
openfl: [3.6.1]
thx.core: [0.40.1]

when i create new openfl project complier by lime ,generate swf ,everything is ok.
but when i add haxelib "thx.core"  in the project.xml,the flashdevelop is auto close :
i found the Exceptions.log :
2016/7/3 星期日 下午 9:16:36
Unhandled exception: 
System.Exception: System.IndexOutOfRangeException: 索引超出了数组界限。
   在 ASCompletion.Model.ASFileParser.ParseSrc(FileModel fileModel, String ba, Boolean allowBaReExtract)
   在 ASCompletion.Model.ASFileParser.ParseFile(FileModel fileModel)
   在 HaXeContext.Context.GetFileModel(String fileName)
   在 ASCompletion.Model.PathExplorer.GetFileModel(String filename)
   在 ASCompletion.Model.PathExplorer.ParseFoundFiles()
   在 ASCompletion.Model.PathExplorer.BackgroundRun()
   在 ASCompletion.Model.PathExplorer.ExploreInBackground()
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()

i think this problem  is  will inevitabely appear, anyone can help me?

**Comment by Neverbirth** [comment]
From the stack trace it seems the parser is crashing when it finds some file, I guess in the thx.core haxelib. I'll try to take a look.

**Comment by Neverbirth** [comment]
I cannot reproduce the problem.

**Comment by Liu-GuangYong** [comment]
Thank you for your test , i try use thx.core lib by source flag, the error is no longer present.

**Comment by Neverbirth** [comment]
Anyway, if you could provide exact instructions on how to reproduce the error it may be useful to fix.

**Comment by player-03** [comment]
I'm still seeing this error. Steps to reproduce:

1. Open [Validation.hx](https://github.com/fponticelli/thx.core/blob/master/src/thx/Validation.hx) in HaxeDevelop.

Alternate steps to reproduce:

1. Create a blank Haxe file in HaxeDevelop.
2. Paste the following:

```haxe
abstract Aaaaaaaaaa {
  aaaaaa function aaa<A>(a: A -> A)
    aaaaaaaa({});

  function aaaaaaaa<A>(a: A, a: A -> A -> A)
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

  aaaaaa function aaaaaaa<A>(a: A -> A, a: Aaaaaa<A>): A
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

  aaaaaa function aaa<A>(a: Aaaaaaaaaa<A, A -> A>, a: Aaaaaaaaa<A>): Aaaaaaaaaa<A, A>
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

  aaaaaaaaaaaa function aaa<A>(a: Aaaaaaaaaa<A, A>, a: Aaaaaaaaa<A>): Aaaaaaaaaa<A, Aaaaaa<A, A>>
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

  aaaaaaaaaaaa function aaaaaaa<Aa>(): Aaaaaaaaaa<Aa, A>
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

  aaaaaa function aaaaaa(a: A -> Aaaa, aaaaaaa): Aaaaaaaaaa<A, A>
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

  aaaaaaaaaaaaaaaaaa function aaaaaaaaaa<A, Aa, A>(a: Aaaa<A, A>, a: A -> Aa): Aaaa<Aa, A>
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

  aaaaaaaaaaaa function aaaaaaaaa<A, A>(a: Aaaa<A, A>, a: A -> Aaaa, a): Aaaa<A, A>
    a
}
```

It turns out that this error is largely based on character count, so I replaced everything with the letter "a." As far as I know, if you delete a single "a" in the above code, the error won't happen. That said, I didn't test all of them, so I don't know for sure. (I mainly tested the long strings, to make sure they actually need to be that long. They do.)

It seems like the keywords "abstract" and "function" are part of the problem, along with angle brackets and curly braces inside parentheses. Each time I removed any of those things, the error stopped happening.

**Comment by player-03** [comment]
If you're experiencing this error and you don't want to wait for a new HaxeDevelop release, add this to [line 14 of Validation.hx](https://github.com/fponticelli/thx.core/blob/master/src/thx/Validation.hx#L14):

```haxe
abstract #if 0 class #end Validation<E, A> (Either<E, A>) from Either<E, A> {
```

`#if 0` is like a comment, except HaxeDevelop doesn't recognize it. That means you can write "`#if 0 class #end`" without any effect on compilation, but HaxeDevelop will think it's dealing with a class rather than an abstract. And as I mentioned above, the "abstract" keyword is part of what causes the error.
