### ISSUE TITLE
[Haxe] NullReferenceException on Renaming a Class

### ISSUE THREAD

**Issue by DleanJeans** [fdorg/flashdevelop#1308]
![screenshot](http://puu.sh/qWfF1/e9b37a8dd1.png)

**Comment by Neverbirth** [comment]
Is this a release binary or debug one? I've also seen it several times recently, but since I was using FD through VS and didn't hear any complaint from anyone else I thought it wouldn't happen in release builds. I think this was due to changes from @SlavaRa? For me it seemed like some threading race condition, I didn't decide to investigate further.

**Comment by SlavaRa** [comment]
I can deal with this problem at the weekend. I found a way to reproduce this.

**Comment by wise0704** [comment]
Anyone looked into this yet?
I did a quick look and I think it might be `ASContext.Context.UpdateCurrentFile()`.
Is the context null when using haxe?
Other than that, the only possible null reference is `ITabbedDocument` object or `SciControl`.

**Comment by SlavaRa** [comment]
fix will be today

**Comment by Neverbirth** [comment]
Please, confirm that this issue is really fixed for you. I cannot right now, will do ASAP.

**Comment by DleanJeans** [comment]
I'm pretty sure it's fixed and fine now.
