### ISSUE TITLE
Release frequency

### ISSUE THREAD

**Issue by andrew-git** [fdorg/flashdevelop#1624]
Last FD release was at Sep 19, 2016.
I use development builds, but often people can't use latest Air and release version of FD and not possible to refer everyone to night builds.
So my proposition make release version at least with Air/FP version updates.

**Comment by wise0704** [comment]
A workaround for target version selection for now:
https://github.com/fdorg/flashdevelop/issues/1603#issuecomment-299401406
Refer to the table in:
http://stackoverflow.com/questions/9537076/chart-of-swf-versions-to-flash-versions

**Comment by andrew-git** [comment]
Personally me have no problem with using night builds or editing configs, but most of users prefer to have actual version. In addition sometime added new features in Air.
Any problems with releasing version about once a month?

**Comment by Neverbirth** [comment]
I wanted to reply to this for some time but always forget for some reason or another. I completely agree with your point, sadly this requires some time @Meychi doesn't currently have. On my side I've also been extremely busy for a few months, now I'm getting more time to dedicate, but I've never done any release (although it's relatively easy from what I know), and I think it's a bit more productive to dedicate time on improving things...

Maybe a FD 5.5 release would make sense, because there are breaking changes coming soon, although for a 5.5 release I would like to see at least a few improvements.
