### ISSUE TITLE
Move line up/down buggy with Arrays of literal objects

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#1626]
Haxe code:
```haxe
class Main 
{	
	static function main() 
	{
		var a:Array = [
			{value: 'a'},
			{value: 'b'},
			{value: 'c'},
			{value: 'd'},
			{value: 'e'},
		];
	}	
}
```

Put the cursor on line with value `e`, press Ctrl-Alt-Up.
Expected result: object values in order a,b,c,e,d
Actual result: object values in order a,b,d,e,c

Problem seems to be triggered by curly braces.

**Comment by wise0704** [comment]
I can reproduce it in both release and development versions.
To add: instead of just the current line, the line above is selected as well, regardless of whether it's MoveLineUp or Down:
![image](https://cloud.githubusercontent.com/assets/13545633/26155545/8255c66c-3b4e-11e7-9543-c484dff7830e.png)

**Comment by asianboi2323** [comment]
Hey! I got a question for you. Your code above contains an array written in multi-line where two brackets [] are not on the same line. Now the problem is that when I use the code-formatter, it compresses all the elements in the array into one line, like "_var a:Array = [{value: 'a'}, {value: 'b'}, ...]_". The code formatter is a good tool but this is really annoying especially when there is a lot of elements in one array. Do you guys have any ideas about how to make multi-line array available so the code-formatter can keep it? Thank you very much.

**Comment by wise0704** [comment]
open a new issue

**Comment by asianboi2323** [comment]
Okay, that's fine, I fixed it. Thanks you.
