### ISSUE TITLE
Auto completion errors when classpath folder structure contains spaces or -

### ISSUE THREAD

**Issue by binkiesjoris** [fdorg/flashdevelop#1657]
We ran into compile problems when a folder structure contained spaces or - signs, this was easily solved by enclosing all compiler arguments with "'s, however, now I'm getting the same errors when triggering auto complete on anything:

> Running process: C:\Programs\HaxeDevelop\Tools\fdbuild\fdbuild.exe "C:\Folder\Folder with space\project.hxproj" -ipc someguid -version "3.4.0" -compiler "C:\Programs\HaxeToolkit\haxe" -notrace -library "C:\Programs\HaxeDevelop\Library" -cp "C:\Folder\Folder with space\Project\libraries"
> Building project
> haxe  -cp "C:\Folder\Folder with space\Project\libraries"
> Build succeeded

Building works, but if you then try to autocomplete something:

> Error: Could not process argument space/Project/libraries
> invalid character: /

I did some testing with an empty new project, but the problem seems to occur whenever I add any reference to the project (either a classpath or the global classpath) that contains a space or -, so it looks like the compiler calls made by the IDE are not enclosed using "'s causing these errors.

This is running HaxeDevelop 5.2.0.3 and Haxe 3.4.0

**Comment by SlavaRa** [comment]
@binkiesjoris I will check it today

**Comment by SlavaRa** [comment]
@binkiesjoris What is your project type(Java, C#, etc)?

**Comment by binkiesjoris** [comment]
@SlavaRa Project type would be javascript.

**Comment by SlavaRa** [comment]
```
Running process: C:\tools\FlashDevelop-development\Tools\fdbuild\fdbuild.exe "C:\projects\Some JS Project In Some Folder\Issue1657\Issue1657.hxproj" -ipc d9a1aff1-8275-4766-b68c-098a4ae3e072 -version "3.4.2" -compiler "C:\HaxeToolkit\haxe" -notrace -library "C:\tools\FlashDevelop-development\Library"
Building Issue1657
haxe --connect 6000 -cp src -js "C:/projects/Some JS Project In Some Folder/Issue1657/bin/Issue1657.js" -main Main
Build succeeded
Done(0)
```
Can you give me your project?

**Comment by binkiesjoris** [comment]
I have created a test case, if you try to autocomplete the test variable in main.hx it should output an error in the console.
[Project.zip](https://github.com/fdorg/flashdevelop/files/1078278/Project.zip)

**Comment by Neverbirth** [comment]
This issue comes from https://github.com/fdorg/flashdevelop/blob/development/External/Plugins/ProjectManager/Projects/Haxe/HaxeProject.cs#L190

Having Quote there looks wrong to me. It makes to classpaths to get double quoted when getting completion, and also makes for example exported HXML files to be wrong. I guess FDBuild should be the one quoting the path here like when we generate the command line for the compiler services.

I'm surprised nobody brought up this error before, but I guess it's not so common to have spaces in project directories, and that most people use HXML or other project files.

**Comment by SlavaRa** [comment]
After #1659 #1829
