### ISSUE TITLE
[Haxe] haxe.exe is kept open

### ISSUE THREAD

**Issue by ncannasse** [fdorg/flashdevelop#1794]
When closing HaxeDevelop, there are several `haxe.exe` process instances which are kept running and needs to be killed by hand. That was not the case in 5.2 where closing it would close all sub processes.

**Comment by Meychi** [comment]
@SlavaRa, @Neverbirth ?

**Comment by SlavaRa** [comment]
I'll check in an hour or two

**Comment by Neverbirth** [comment]
The times I've seen this happening are caused by https://github.com/HaxeFoundation/haxe/issues/6324.

I don't know if this is the same case or not.

**Comment by ncannasse** [comment]
They are not in infinite loop. When i start haxedevelop 5.3 it opens a
haxe.exe process, when I compile it starts another one. When I quit there
is one remaining.
They might be processes having output which is not being read by HD, so
they are on hold until the output is processed.
Processes should not be detached from main HD/FD process so they won't
outlive it.

**Comment by dkolyesnik** [comment]
I have a similar issue. 
When I launch Haxe Develop and it opens the last opened project, it creates multiple haxe.exe process instances. When I close HD it kills only one haxe.exe. Compiling do not increase the number of haxe.exe processes though.
And it look like the number of processes HD opens at startup equals to the number of opened .hx files in the project. 
Opening HD via .hxproj file do not lead to extra haxe.exe instances. I guess it's because in this case there are no open .hx files from the start.
Windows 8.1, Haxe 4, HD 5.3.2.1 and 5.3.3.1 .

**Comment by dkolyesnik** [comment]
The number of haxe.exe instances is not equal to .hx files, but there is clearly a dependency. More files opened lead to more processes.

**Comment by dkolyesnik** [comment]
And it not depens on the type of the project, I tryed several with different Platform settings and the result is the same

**Comment by JoeCreates** [comment]
I have this issue when "Completion Mode" is set to CompletionServer, but not if I use one of the other two completion modes. What's worse is that it seems to create a LOT of haxe processes over time.

**Comment by dkolyesnik** [comment]
Yes, I also have this problem only when using the CompletionServer mode.

**Comment by JoeCreates** [comment]
On a related note, is the completion meant to be cached? I have projects with many macros and it takes like 5-10 seconds to bring the autocomplete up with the macro generated properties. In VSCode it's basically instant because it's cached. Is there an option to turn on a cache somewhere or is this something which needs to be added?

**Comment by ncannasse** [comment]
@JoeCreates when mode is set to CompletionServer you should get cache results. But this requires a first successful compilation. In VSCode I think it's automatically triggered upon opening the project.
