### ISSUE TITLE
[x64] Invisible items in macros menu

### ISSUE THREAD

**Issue by profelis** [fdorg/flashdevelop#2911]
I just installed latest nightly haxedevelop build and all items in Macros menu are invisible

![image](https://user-images.githubusercontent.com/250935/68932160-b0282380-079a-11ea-89ba-a84130fb0ce3.png)
![image](https://user-images.githubusercontent.com/250935/68932176-b74f3180-079a-11ea-9437-3b412d210357.png)

os: windows 10

**Comment by hachigoro** [comment]
Same here, it happened since I moved to 5.3.4.x. Not only they are invisible, but macros don't work either. One of the macros I use had a button shortcut on the main toolbar, and the button has disappeared.

![empty_macros](https://user-images.githubusercontent.com/2738647/73293617-111ba100-41b9-11ea-8083-781fde88261f.png)

**Comment by hachigoro** [comment]
I have also tried the 32 bit version, and have the same issue. Uninstalled 5.3.4 and installed 5.3.3, and the issue is still present in both 32 and 64.
