### ISSUE TITLE
Add "Copy as Tree" commands to FlashDebugger

### ISSUE THREAD

**Issue by hgupta9** [fdorg/flashdevelop#602]
I have developed a "Copy As Tree" command for the FlashDebugger plugin. I just need someone to integrate it into the main code base. Its a very useful feature to have, and is totally unique, even VS does not have such a command.

I have tested it for months, so its very stable, and does not hang-up even in the most complex object trees. I have uploaded the code with annotations so its easy to tell which parts are new, edited or removed. Can someone please do the needful.

ZIP with code here:
https://app.box.com/s/avab0z5anxezz2o64lppqeye27tchxbf

Notes and screenshot here:
http://www.flashdevelop.org/community/viewtopic.php?f=4&t=12151

**Comment by elsassph** [comment]
This looks interesting, but if you managed to write this patch, why not create a pull request?

**Comment by hgupta9** [comment]
If someone could add it in I would be grateful. Nevertheless, I shall try to create a pull request. Never did it before.

**Comment by elsassph** [comment]
Eh that's still a good idea ;)
You really should look into creating a pull requests - that's easy enough and nowadays that's how we work!

**Comment by hgupta9** [comment]
Thank you, I will figure it out. Cannot be so difficult after all! Keep learning new things ....

**Comment by hgupta9** [comment]
Is it correct? I forked FD repo into my account (https://github.com/hgupta9/flashdevelop) and now I have cloned it to my desktop. Now after I change this I'll create a pull request. Is that correct? Or should I not fork FD repo?

**Comment by hgupta9** [comment]
I hope I've done it right
https://github.com/fdorg/flashdevelop/pull/603

**Comment by elsassph** [comment]
You did it ;)
On first sight I see you didn't follow the coding style which is a bit annoying because someone will have to reformat that. We recommend using Visual Studio default formatting options to contribute code.
Aside from that, a PR will allow us to discuss the changes with you - for instance the StringHelper class should probably be commented a but if that's a public helper class.

**Comment by hgupta9** [comment]
Are you planning on merging it? How are such things handled? Do you wait a specified time for discussion before accepting PRs?

**Comment by elsassph** [comment]
Yes I mean braces on next line. A good practice when you contribute to some project is to follow formatting and naming style.

We will now review this PR (I didn't have the time yet) and maybe ask you yo make a few minor changes.

Oh I see you created a PR against 'master', which is the currently released FD. Normally you should always do PRs against the 'develop' branch of a project, which is the next release of the project. And in the case of FD I'll ask you to created the PR against 'fd5' branch because we don't add features to FD4.x anymore (only bug fixes).

So I'm sorry to ask you that but I'm afraid you have to change the branch you were working on to 'fd5', apply your patch and do the PR again.

PS: I advise you to learn git best practices: 
http://nvie.com/posts/a-successful-git-branching-model/

**Comment by hgupta9** [comment]
No problem. Why don't you review it first, then I'll make whatever changes are needed and create a final PR against fd5.

**Comment by hgupta9** [comment]
Created semi-final PR https://github.com/fdorg/flashdevelop/pull/608 - Hope everything's ok.

**Comment by hgupta9** [comment]
Created final PR https://github.com/fdorg/flashdevelop/pull/616 - All points taken into account. We should be ready to go.
