### ISSUE TITLE
a bug of autocomplete

### ISSUE THREAD

**Issue by matrix3d** [fdorg/flashdevelop#617]
![rtx](https://cloud.githubusercontent.com/assets/4150631/6540547/5d389902-c4dd-11e4-8aa1-8c3bc1e8e521.jpg)

get error

**Comment by Meychi** [comment]
What's the error? OS and FD version?

**Comment by Neverbirth** [comment]
I guess that the completion list is not appearing? I've noticed this bug as well when there is a Vector used around, I guess the file parsing doesn't like something about that. If you comment the info.arguments line it will work again, and after adding some more code uncommenting the line won't stop the completion list to appear.

I've seen this on FD5, but surely 4.7 will behave the same (maybe 4.6 as well).

**Comment by matrix3d** [comment]
@Neverbirth  yes.it is can fixed?

**Comment by Neverbirth** [comment]
Can it be fixed? of course, will it be fixed? it depends...

The problem is in ASFileParser as I said, the problem is that info is identified as the right type first, but then when the second line is parsed, it gets confused because of that Vector.<String>(args.split(" ")) and creates a new info model with Vector.<String>(args.split(" ")) as its type.

**Comment by Neverbirth** [comment]
I'd say this can be closed now.
