### ISSUE TITLE
File > Restart often just closes FD, doesn't restart it

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#855]
For me, the File > Restart command only works about half of the times. At other times, FD is closed but doesn't restart, I have to restart manually.

**Comment by Meychi** [comment]
This .NET feature is not super stable, but i'd like to improve it in the future.

**Comment by markknol** [comment]
Maybe it can be removed from the menu instead of disable the function.

**Comment by Neverbirth** [comment]
I'd say this shouldn't be disabled or removed but fixed, because the user should have the option to restart after downloading plugins and some other stuff from AppMan, but as Mika says, this is a known and documented .NET bug. Maybe some small helper utility should be added that is launched on calling Restart, and once that one detects that FD is closed it should run FD again.
